var arbol = new BST();
arbol.agregar(new Producto(15));
arbol.agregar(new Producto(10));
arbol.agregar(new Producto(2));
arbol.agregar(new Producto(20));
arbol.agregar(new Producto(12));
arbol.agregar(new Producto(16));
arbol.agregar(new Producto(23));
arbol.agregar(new Producto(18));
arbol.agregar(new Producto(0));